### ISSUE TITLE
Approval workflow: Overview

### ISSUE THREAD

**Issue by amercader** [CivicActions/ckanext-ed#11]
This is a meta-issue. We'll split the feature into different, smaller tasks

### Personas:

*Note*: Whenever we use "Office" we mean CKAN's "Organizations"

* **Sysadmin**: has permissions over the whole site and across all datasets
* **Office Admin**: has permissions over all datasets in a particular organization. can manage membership (ie can add/remove other users to the office with different roles). Can change the review status of datasets in a particular office.
* **Office Editor**: can create and edit datasets in a particular office
* **Logged in-user**: a user on the site that doesn't belong to a particular office and is not a sysadmin
* **Anonymous user**: a non-logged in visitor on the site.

### Overview:

Office Editors can create datasets, which will be always flagged as "pending approval". Office Admins (and maybe Sysadmins) receive an email notification when a new dataset requires approval. They choose to approve it (and optionally publish it) or reject it, providing feedback. The Editor receives a notification either way.

*Note*: The approval state of a dataset is not related to the value of the Public/Private property. Editors will define this as any other field (they may be asked by Admins to make a dataset private before approval of course). Ie a dataset that is intended to be published as private still needs to go through the approval process.

### Detail:

* When an Editor creates a dataset, it is created on a pending state. 

    - UI: Notice on the form about the dataset needing review
    - Custom validator for the `state` field that ensures that if you are not an Admin/Sysadmin the state is always `approval_pending`

    Other requirements:
    - Datasets with state set `approval_pending` should not be displayed in the search results (`/dataset` or API)
    - Logged-in and Anonymous Users should not be able to access a pending dataset (UI or API). Extend the `package_show` auth function (if necessary)

* An Administrator receives a notification, an email including the user that created the dataset and a link to the dataset page.

    - Send Email notification to all Office Admins (**Question**: also to Sysasdmins?) Override `package_create` and check the `state` field to decide if is necessary to send the notifications

* An Administrator visits a dataset pending review. On that page they can review the metadata provided, and Approve or Reject the request.

    - If the visitor is an Admin for the Office the dataset belongs to, they are shown two buttons: Approve and Reject. The latter has a small text field to provide feedback
    - If the visitor is the orignal Editor, they can edit the dataset, but they see a notice that their changes still need to be approved.
    - If the visitor is Logged-in or Anonymous User, they should get a 404 
    - There is a custom controller with two endpoints, one for approval and one for rejection. These call `package_patch` as needed to set it to `active` or `approved` (see Q below)

    **Question**: Is it up to the Administrators or the Editors to finally Publish the dataset? Ie can Administratos Publish the dataset at this point?

* The Editor gets a notification of the outcome, containing the Admin user that took the action, the action taken (approval or rejection), feedback if any, and a link to the dataset page.

    - Send email notification to the original Editor (that should be in `creator_user_id`)

* Editors can choose to delete the dataset (no furhter action needed) or to change the metadata according to the feedback. In this case, another notification is sent to the Admins telling that the pending dataset has been updated (Override `package_update`)

* All these actions are logged in an internal workflow table, containing:
    - Dataset Id
    - User Id
    - Action
    - Timestamp
    - Comment

    For instance:
        Editor X created Dataset A on time T1
        Admin Y rejected Dataset A on time T2 with comment 'aa'
        Editor X updated Dataset A on time T3
        Admin Y approved Dataset A on time T4

* There is a separate page available to Admins, where they can see all current requests for the offices they manage. A good place for this could be a tab in the dashboard
    - The page shows a list of pending datasets, with a link to each dataset page

* Editors can see the pending reviews that they submitted on the My Datasets tab in their dashboards.

TODO: things to clarify:
* Approval vs Publication

**Comment by zelima** [comment]
Think this can be closed as FIXED now
