### ISSUE TITLE
Discovery: Check Boostrap 3 support on IE11

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#110]
Description:  We need to make sure that Bootstrap 3 is well supported on Internet Explorer 11 as it's one of the widely used browsers in the department along with Chrome.

Bootstrap Version used: 3.3.7

## Manual Tests on IE 11

* [x] Bootsrap Compontents (Accordions, Navbars etc.)
* [x] Bootstrap Theming Styles (Buttons, colors classes, alerts) 
* [x] Bootstrap grids 
* [x] Bootstrap Javascript functions (modal etc)

Links Used for testing
* Components and & Theme Styles: https://getbootstrap.com/docs/3.3/components/
* Grids: https://getbootstrap.com/docs/3.3/css/
* Javascript elements: https://getbootstrap.com/docs/3.3/javascript/
* Other websites used for testing: https://datahub.io (Built in Bootstrap)

## Official Statement from Bootstrap  

As stated on https://getbootstrap.com/docs/3.3/getting-started/ ,  "On Windows, bootstrap support Internet Explorer 8-11."
![image](https://user-images.githubusercontent.com/13431329/57377688-aeb0e980-71c0-11e9-892f-844fe178c687.png)

## Testing Core CKAN on IE11

URL used for test: https://demo.ckan.org/

All the bootstrap functions and structure related items of CKAN were tested and found to be working well with IE 11.  No issues in the core design were found. 

## Closing Comments

The Bootstrap 3 and CKAN are very well supported by the Internet Explorer 11. 

However, the libraries that will be used for animating particles or other visual effects were not tested in this report as the choice of those libraries is yet not finalized and multiple alternatives can be considered.

**Comment by zelima** [comment]
FIXED
