### ISSUE TITLE
Style CKAN footer with USWD 2.0 and mockups

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#112]
Enable the USWDS styling onto the Menu.  

Jira:  https://open-data-ed.atlassian.net/browse/OD-182

From:
![image](https://user-images.githubusercontent.com/13431329/57430572-c5e9e880-724d-11e9-8087-4169aca95724.png)

To:
![image](https://user-images.githubusercontent.com/13431329/57430584-cedaba00-724d-11e9-8afa-60d7b2f9956c.png)

**Comment by zelima** [comment]
FIXED
