### ISSUE TITLE
Send email notifications when a pending dataset is requested

### ISSUE THREAD

**Issue by amercader** [CivicActions/ckanext-ed#13]
More context in #11 

When a dataset is created with an `approval_pending` state, send an email notification to all Admins for the organization/office it belongs to

- [x] Extend the `package_create` action and check for the value of the state field. If it's pending, get all admins for the organization the dataset belongs to (`owner_org`) using [`member_list`](https://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.member_list).
- [x] Send an email to all admins. Use a template for the body, which should contain:
  * Name of the user that created the dataset
  * Basic info on the dataset (maybe Title and description)
  * For now a link to the dataset page

Next we'll tackle what happens when admins get to the dataset page.

**Comment by zelima** [comment]
FIXED
