### ISSUE TITLE
Regression bug: "Sort" changed to "Order By" again, in latest master

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#138]
As per design, "Order By" was changed to "Sort" in the search results snippet in this PR:
- https://github.com/CivicActions/ckanext-ed/commit/ee32799d7ea952c9524d7adbf0dffa1acb362a30

But, latest HEAD on master shows:

![image](https://user-images.githubusercontent.com/310789/57981393-838b8d00-7a3f-11e9-8c01-c61a3976ea20.png)

**Comment by zelima** [comment]
This is now FIXED I believe
