### ISSUE TITLE
Edit the dataset navigation to match mockups

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#146]
We need to edit the links in the navigation to match the mockups.

1. Links to be Data, Docs, Discuss (page not ready yet, put a # or temp link to somewhere), Usage
2. The links should be able to accept icon "images", you can start with a .png file or something.

Currently: 
![image](https://user-images.githubusercontent.com/13431329/58079618-07c04a80-7bcf-11e9-9930-6c0c1b18acb4.png)

Desired Output: 
![image](https://user-images.githubusercontent.com/13431329/58079647-17d82a00-7bcf-11e9-880a-1029d2a2df36.png)

**Comment by tanvirchahal** [comment]
we need to show custom images along with the link,  see the mockup,  there is an image next to discuss, usage, data etc.
these images/icons are not built in into ckan,  so need to be able to specify icon path

**Comment by metzgr** [comment]
I don't know if I ever specified this, but the mockups are using material icons. The best way to incorporate would be to use their icon font https://google.github.io/material-design-icons/

**Comment by zelima** [comment]
FIXED
