### ISSUE TITLE
Fix unit testing

### ISSUE THREAD

**Issue by roll** [CivicActions/ckanext-ed#2]
# Overview

For now, unit tests are set up to be run inside the test docker container. All good except for that `--with-pylons=test.ini` makes it unresponsive.

It works without it for simple tests though.

**Comment by roll** [comment]
@amercader 
I've put all the commands to `package.json` (maybe should be switched to `Makefile`) to use a knowledge base and minimize the time for getting people up and running (esp. not Pyhon people).

The command:
```
docker exec -t dockerckaned_ckan-dev_1 bash -c 'cd /srv/app/src_extensions/ckanext-ed && nosetests --nologcapture'
```

**Comment by zelima** [comment]
FIXED
