### ISSUE TITLE
Disallow Search Engine crawlers on Ed Portal

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#202]
During the initial launch of the portal going live, the search engine crawlers must be disallowed.

### User Stories:

As Dept of Ed, we want to launch the ed portal with search engines blocked, so that the portal cannot be accessed via google for initial launch

As Dept of Ed, the search engine crawlers are required to be blocked for launch, so that initial bugfixes can be made before making the portal accessible to search engine traffic. 

### Acceptance Criteria:

* [ ] Search Engine robots.txt file is created
* [ ] Search Engine Crawlers are prevented to crawl the website

**Comment by nightsh** [comment]
Closing this as not applicable to the Admin UI / the CKAN Classic interface is only visible to logged in users, unauthenticated requests (such as crawling bots) will be redirected to the NG frontend. A [corresponding issue](https://gitlab.com/datopian/dept-ed-frontend/issues/16) has been created and [dealt with in a PR](https://gitlab.com/datopian/dept-ed-frontend/merge_requests/11) in the [NG frontend repository](https://gitlab.com/datopian/dept-ed-frontend).
