### ISSUE TITLE
Discovery: Default behaviour when no Organisation (called Publisher on platform)

### ISSUE THREAD

**Issue by estebanruseler** [CivicActions/ckanext-ed#231]
# Description

There are many times where the organisation is not present so the harvester eneters "harvester organization". EG https://us-ed-testing.ckan.io/dataset/safe-map What is interesting is that the data.gov site has Dept Ed as the organisation. 

This is a discovery ticket to find out:

 - [ ] The harvester for data.gov: does it default all datasets that do not have an organization with Dept Ed?
 - [ ] The Dept Ed harvester (that we configured) why does it populate the Org as "Harvester Organization" I presume this is a default behavior?
 - [ ] Quickly assess if it is possible from the metadata available to populate the from the information there (eg NSCS) 

Needed by end of the day Argentine time on Monday. 

# Snippet from the documentation: 

remote_groups: By default, remote groups are ignored. Setting this property enables the harvester to import the remote groups. There are two alternatives. Setting it to 'only_local' will just import groups which name/id is already present in the local CKAN. Setting it to 'create' will make an attempt to create the groups by copying the details from the remote CKAN.

remote_orgs: By default, remote organizations are ignored. Setting this property enables the harvester to import remote organizations. There are two alternatives. Setting it to 'only_local' will just import organizations which id is already present in the local CKAN. Setting it to 'create' will make an attempt to create the organizations by copying the details from the remote CKAN.

**Comment by estebanruseler** [comment]
From Andres: It seems like you need to have 1 organisation per harvest source.

**Comment by avdata99** [comment]
At the _import_stage_ we define this behaviour: https://github.com/avdata99/ckanext-datajson/blob/us-ed/ckanext/datajson/harvester_base.py#L586-L589.

**Comment by avdata99** [comment]
_The harvester for data.gov: does it default all datasets that do not have an organization with Dept Ed?_

When you add a new harvest source to data.gov you **should** define an Organization. Each harvest source has an organization. It's a required field. 
Data.gov **do not change its default behaviour**. We just change for Dept of Ed DataJSON harvester. If Data.gov harvest from https://www2.ed.gov/data.json (or any new source) they are going to set as dataset's organization the organization they set when they add this harvest source.

_The Dept Ed harvester (that we configured) why does it populate the Org as "Harvester Organization" I presume this is a default behaviour?_
 - The default behaviour is to set the organization of each new dataset to the Organization of the harvest source. "Harvester Organization" was used as a default org in firsts tests. That what we see this organization in the 469 datasets.
Using the [new config options](https://github.com/datopian/ckanext-datajson#harvest-source-configuration) you could set _publisher_ as an organization in CKAN. This is only for the Dept of Ed CKAN instance, not for data.gov. They use another harvester version.

_Quickly assess if it is possible from the metadata available to populate the from the information there (eg NSCS)_
We already harvested the Dept of Ed source in our test env: https://us-ed-testing.ckan.io/dataset

Publisher as organizations solved at #235.
