### ISSUE TITLE
508 Round II

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#233]
Resolved: 26
Partially Resolved: 2
Unresolved: 10

## Partially Resolved

* [x] 1. Skip nav link hidden from all users  (done)
    * **Note:** Skip nav link is made to show when selected, keep on hitting the tab until the skip to nav is visible. Ensure to hard refresh.
![image](https://user-images.githubusercontent.com/13431329/70973680-f521cd00-205a-11ea-81a4-89ca19dd949e.png)

* [x] 13. Checkboxes are selectable by keyboard, but do not function [Victor ?]

## Unresolved
* [x] 11. dropdown menus missing explicit ```<label>``` elements  (rechecked, labels exists)
    * **Note:** No changes were made, the labels are exisiting and have a "for" attribute to the corresponding dropdown. Clicking on the label shifts the focus to the dropdown.
![image](https://user-images.githubusercontent.com/13431329/70973846-577acd80-205b-11ea-999c-b65757e40123.png)
![image](https://user-images.githubusercontent.com/13431329/70973936-898c2f80-205b-11ea-8d43-f00b76b8c457.png)

* [x] 14. Checkboxes are missing explicit ```<label>``` elements (done)
    * **Note:** All the checboxes now have labels with dedicated "for" attributes 
* [x] 15. ```<ul>``` elements must only contain ```<li>``` elements (done) 
    * **Note:** To avoid this validation issue, the structure has been changed to not use any ```<ul>``` or ```<li>``` tags, the sidebar is now rendered with divs only.
* [x] 36. Invalid ARIA Value (done)
    * **Note:** ARIA role value updated to "navigation"

**Comment by nightsh** [comment]
Closed in #234
