### ISSUE TITLE
Havester to input Organization based on Publisher in datajson file

### ISSUE THREAD

**Issue by estebanruseler** [CivicActions/ckanext-ed#235]
Description: The Harvester currently default to 1 org value when setting up harvester (defaulted to Harvester Org), we want to change it so that when the metadata is harvested the correct organisation (not default) is input. 

Acceptance critiera:
 - [x] Each publisher metadata field is input using the organisation metdata in the datajson file

**Comment by avdata99** [comment]
Fixed [here](https://github.com/datopian/ckanext-datajson/commit/f7bdf139a8bee51bb448dc4b309d423d0bbdbce5)

Creation of _organizations_ from _publishers_ now is possible with the config `"organization_from": "publisher"`.  

Then custom schema from Dept of Ed is activated whit the `"mapping_fields": "dep_of_ed.json"` config.

Also we require default values to work. 
Recommended final config:

```
{
  "defaults": {
    "private": false,
    "author": "Unknown author",
    "author_email": "unknown@email.com",
    "spatial": "United States"
  },
  "mapping_fields": "dep_of_ed.json", 
  "organization_from": "publisher"
}
```

**Comment by avdata99** [comment]
Reharvesting is not duplicating datasets: https://us-ed-testing.ckan.io/harvest/www2-ed-gov/job/9174cbbb-1d1a-4cc4-827e-647910a2c06e

![image](https://user-images.githubusercontent.com/3237309/71599157-6fa51f00-2b28-11ea-98de-e7da34e99541.png)

Still need to test if new organization from publishers works as we expect

**Comment by avdata99** [comment]
It's done. We harvest and each datasets uses the _publisher_ as _organization_

![image](https://user-images.githubusercontent.com/3237309/71625076-9749c500-2bc4-11ea-9879-29a028dad0ee.png)

![image](https://user-images.githubusercontent.com/3237309/71625154-0d4e2c00-2bc5-11ea-96ee-f768ede0ccb8.png)

New documentation about this config values added:
![image](https://user-images.githubusercontent.com/3237309/71625378-3cb16880-2bc6-11ea-8496-1fae23655ba6.png)


If the client validate the changes @estebanruseler we can close this issue.
