### ISSUE TITLE
Missing groups from harvested datasets

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-ed#240]
When harvesting, the created datasets are missing the groups information fro their metadata.

As a user, I am expecting to see groups added to the datasets created after starting the harvesting process. Most of the groups should already exist in the database, but in case they don't, they need to be created.

What happens instead is that the datasets are created with no groups.

Acceptance criteria:

- [ ] have groups property populated for harvested datasets

**Comment by avdata99** [comment]
In [ckanext-harvest](https://github.com/ckan/ckanext-harvest) the _remote_groups_ config option indicates:

**remote_groups:** By default, remote groups are ignored. Setting this property enables the harvester to import the remote groups. There are two alternatives. Setting it to 'only_local' will just import groups which name/id is already present in the local CKAN. Setting it to 'create' will make an attempt to create the groups by copying the details from the remote CKAN.

I added this config if our [testing harvest source](https://us-ed-testing.ckan.io/harvest/www2-ed-gov/job/last), clean and start a new harvest process. If the groups now are harvested with groups we can close this

**Comment by avdata99** [comment]
Issue redefinition: If a _keyword_ in the source (_tag_ in CKAN dataset) exists as a group, then add this dataset to this group

**Comment by avdata99** [comment]
Mounted a local env.
Created some topics (groups) already existing as _keywords/tags_:
![image](https://user-images.githubusercontent.com/3237309/72182724-d64cf700-33ca-11ea-8875-735d06bb8aa8.png)

It works, connect the harvested datasets with topic/groups when exists.
Added notes to README for this new setting
