### ISSUE TITLE
Pending datasets notification appears on editors

### ISSUE THREAD

**Issue by amercader** [CivicActions/ckanext-ed#27]
![screenshot_2018-12-10 manage - dave office editor - users - u s department of education](https://user-images.githubusercontent.com/200230/49734621-236d0f80-fc85-11e8-8c91-01bf85fb98a4.png)

Editors will eventually see some notifications (ie when their datasets are approved or rejected) but right now they should not see any notification, as the dashboard doesn't include anything for them.

**Comment by zelima** [comment]
FIXED
