### ISSUE TITLE
Use state instead of approval_state 

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#28]
I did not see this when implementing but now I think there's no real need to use  `approval_state`, to flag pending datasets, but already existing `state` is pretty much enough (plus it's easier to get - directly from models). Also, probably will be easier when we work on approve/publish workflow 

@amercader wdyt?

## Tasks

* [ ] replace `approval_state` with `state` everywhere in code
* [ ] update tests

**Comment by zelima** [comment]
hm... Started on refactor and it does not seem as easy as I thought:
* `package_show(context, data_dict)` raises `NotAuthorized` if `state` is not active and user is anonymous or member 
* `packge_search(context, {'fq': 'state:approval_pending'})` - just not acceptas this :) - always retun empty list
* Actual state won't dissapear from datasets metadata
![image](https://user-images.githubusercontent.com/15143785/49785783-17438980-fd3b-11e8-9969-a1c45a0733a8.png)

I can go further and debug, but don't think we need this that much. Probably close as WONTFIX?

**Comment by amercader** [comment]
Yes, I think `state` is too embedded in CKAN's core logic. Let's use the separate field for now and we'll revisit if we find any issue.
