### ISSUE TITLE
Metadata is no longer mandatory in backend

### ISSUE THREAD

**Issue by Daniellappv** [CivicActions/ckanext-ed#282]
## Description

In order to facilitate the scraping exercise, we should remove the validation rules for mandatory fields so they are not required in the backend. In other words, we are going to punch a hole through the validation system to allow the harvester through with minimal requirements. We might revert this later on, so ideally it could be easy to get them back in one git operation.

## Acceptance criteria:

* [x] We can add a data profile, collection or source with only the name (no other metadata required)  
* [x] We have created a card to re-introduce these rules in the front end (eg JS rules) - DONE, see #283 

 ## Task-list:

* [x] Note the current rules here https://open-data-ed.atlassian.net/browse/OD-486

**Comment by nightsh** [comment]
Closed by f34844762096624cd08adeb9c03b0814a164ee96
