### ISSUE TITLE
Add option for admins to make datasets public on approval

### ISSUE THREAD

**Issue by amercader** [CivicActions/ckanext-ed#34]
Right now admins see two buttons on a pending dataset: Approve and Reject. We need to add the option to make the dataset public as well

- [x] If and admin goes to a pending dataset page *and the dataset is Private*, show three buttons: "Approve and keep private", "Approve and make public" and "Reject". If the dataset is public show the current two
- [x] Change the approve endpoint to take the private aspect into account. If make public is true and the dataset is private, change it to public (`private=False`)
- [x] Add a helper text on the dataset form for the Visibility field (you do that in the `schemas/dataset.json` file): "Datasets are private by default, meaning only members of the same office and administrators can access them. If made public, once approved all users of the site will be able to access and download them.".

**Comment by zelima** [comment]
@amercader
> Add a helper text on the dataset form for the Visibility field (you do that in the schemas/dataset.json file): "Datasets are private by default, meaning only members of the same office and administrators can access them. If made public, once approved all users of the site will be able to access and download them.".

Tring following but it's just creating a new field (like state). How to override the default field?

```
{
      "field_name": "private",
      "label": "Visibility",
      "required": true,
      "help_text": "Datasets are private by default, meaning only members of the same office and administrators can access them. If made public, once approved all users of the site will be able to access and download them."
},
```

**Comment by zelima** [comment]
@amercader what do you mean by " owner_org form snippet." which snippet exactly? This one does not seem to be related https://github.com/ckan/ckan/blob/df35eec2f5229bc60176cf96dc83ca1fcc259d1e/ckan/templates-bs2/organization/snippets/organization_form.html

Neither modifying this gives anything https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/package_basic_fields.html#L93

**Comment by amercader** [comment]
Sorry. I should have been clear. This site uses [ckanext-scheming](https://github.com/ckan/ckanext-scheming/) to define the metadata schema (the fields that appear in the form, how are they validated and rendered). That's why we have a [dataset.json](https://github.com/CivicActions/ckanext-ed/blob/master/ckanext/ed/schemas/dataset.json) file. This extension doesn't use the form included in core but rather renders snippets for each field that are either located on [ckanext-scheming itself](https://github.com/ckan/ckanext-scheming/tree/master/ckanext/scheming/templates/scheming/form_snippets), or in our own extension if we need to override them.

We currently aren't overriding any snippets, so we'll need to create a `scheming/form_snippets/` folder in our templates folder. Then you can create a `organization.html` snippet that extends the [default one](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/form_snippets/organization.html). We probably just need to override the `package_metadata_fields_visibility` block to add the helper text.

Does this make sense?

**Comment by zelima** [comment]
@amercader Yes, that explains a lot. Thanks!
