### ISSUE TITLE
Discovery: Account Federation for easier login

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#44]
Need to determine level of effort and complexity in having users use their ed.gov email addresses & PW’s as login creds for CKAN.

User story 1 : As a Dept Ed employee who needs to have access to the portal, I want single sign-on using my Dept Ed credentials so that I don’t need to enter another password and can easily gain access to the portal

User story 2 : As the development team, I want single DeptEd to have single sign-on using their Dept Ed credentials so that the project team doesn’t need to comply with security protocols for credentials etc

Checklist:

- [x] Investigate data.gov single sign-on, maybe connected to Drupal?
- [x] What kind of request need to be sent (Maxgov?)
- [x] If they are using Oauth then we can build upon pre-existing extension
- [x] Estimate what work is involved and how long this will take
- [ ] ~~Test~~

## Analysis 

https://www.data.gov/login redirect me to https://login.max.gov/cas/login. I can't find any relation of max.gov and auth0 neither on google, [Auth0](https://auth0.com/docs/identityproviders) or max.gov website. So I guess we will have to go the hard way

This is the [tutorial for authenticator for Salesforce using OMB Max](https://github.com/GSA/OMB-Max-Auth-for-Salesforce) (thanks to @nightsh ). It's providing the step to step instructions of how to configure "salesforce" portal and intagreate it with MAX account. Follwoing that max.gov seem to be using saml2 for single sign on (unless it's outdated - last commit 2 years ago, but hope). 

Luckily (thanks to @amercader) we have [ckan extension](https://github.com/okfn/ckanext-saml2) for saml based providers. As suggested it worked well with few other projects. I've also managed to install it locally into the ED project and looks like it's working (with errors, but looks promising). Of course I could not test it actually working as we need to set up a dummy project on max.gov to see it in action.

### Estimated work 

- We will probably need to update ckanext-saml2 to be compatible with ckan 2.8.x [1d]
- Lear how saml2 authentication actually works for max.gov [3d]
- create a dummy project on max.gov to play around and test (or get access to existing if possible) [1d]
- Play around with ckanext-saml2 and understand how things work [3d]
  - configure ckan properly 
  - send requests
  - get users
- spec out how we are going to implement [1d]
- Tests [1d]
- Implementation [5d]
- More tests [1d]
- Review QA [1d]
- Deploy to production [1d]
- User tests

TOTAL:  18D + 20% (3 weeks)

## QA:
Q: What does data.gov use for single sign-on?
A: MAX Authentication Services

Q: Connected to Dupal
A: No

Q: What kind of request need to be sent (Maxgov?)
A: Not quite sure what is the exact question here. but 
- MAX Authentication Services will be acting as an Identity Provider (Idp) for us. They are using SAML 2.0  protocol for exchanging information. I guess we will be sending HTTP POST requests

Q: Are they using Auth0?
A: No

Q: Estimated tie
A: 3 weeks

**Comment by nightsh** [comment]
@zelima reading the source code here might provide some insights: https://github.com/GSA/OMB-Max-Auth-for-Salesforce

**Comment by amercader** [comment]
This is probably not relevant but adding so it's on your radar:

* [ckanext-saml2](https://github.com/okfn/ckanext-saml2) allows login from saml2 based providers (this was originally developed for data.gov ages ago). It has worked well on a couple of recent projects, so if Saml2 is an option, this is worth exploring
* [ckanext-ldap](https://github.com/NaturalHistoryMuseum/ckanext-ldap) supports logging in from LDAP servers. Again has worked well for me in the past, but needs work to support CKAN 2.8

There are other auth plugins for OAuth and ADFS (an azure acitve directory thing) but I don't have experience with them

**Comment by zelima** [comment]
@amercader @nightsh I also found this extension https://github.com/GSA/ckanext-saml2 maybe looks familiar?

**Comment by amercader** [comment]
@zelima the okfn fork that I linked is an improved version of the GSA one

**Comment by zelima** [comment]
Think [ckanext-saml2](https://github.com/okfn/ckanext-saml2) and https://github.com/GSA/OMB-Max-Auth-for-Salesforce is really the way to go here. At least worth to explore deeper. @amercader Is it possible to share the projects you are talking above, so I can take a look there as well

> It has worked well on a couple of recent projects

**Comment by akariv** [comment]
@zelima from what I gathered from our GSA partners, there are OMB max.gov and the newer login.gov https://login.gov/developers/

We should probably ensure that they want it implemented with the _old_ system and not the new one (both seem to be using saml2 so in theory it shouldn't be much of a difference).

Otherwise plan looks good.

Note that we have a very similar issue in data.gov (https://github.com/ViderumGlobal/ckan-cloud-docker/issues/1), so a generic solution that works for both would be god. At least, we should have a clear documentation on how this was set up, both technically and externally (e.g. setting up a dummy max.gov project).

**Comment by zelima** [comment]
WONTFIX. Will be implemented by PH folks
