### ISSUE TITLE
Help text: Clarification on what to enter for fields

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#61]
Jira:
* https://open-data-ed.atlassian.net/browse/OD-88

Description: there would be text in smalller font under the field titles to help user know what the field is. TBA Need the help copy and need the font size.

As a data steward, I want to correctly enter the data so that the dataset I publish is accurately described.

Estimates:Dev team - 1 dayIvan - 4 hours ❓

**Comment by zelima** [comment]
@sivang is there anything remaining here?

**Comment by zelima** [comment]
FIXED
