### ISSUE TITLE
Bug: Email validation

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#64]
Jira:
* https://open-data-ed.atlassian.net/browse/OD-110

The email address field does not require a properly formatted email address. No error is thrown if an invalid format is entered.

As a user, I want to input in email field to be validated before I save, so that I accidentally don’t enter info for other field

Checklist

Create the custom validator to check for email validity (if not exists)

Update schema

Tests

Deploy

**Comment by sivang** [comment]
## Investigation:
* CKAN does have an email validation function, but not sure if it's use and where and to what extent.

ckan.logic.validators.email_validator(value, context)
Validate email input

Discussed with @wardi some stuff around it , but perhaps there's a built in thing already available that's not documented for templates.

**Comment by wardi** [comment]
`email_validator` can be added to any schemas on any new or existing field. If you're using scheming just add it to the "validators" , e.g. `"validators": "scheming_required email_validator"`

**Comment by sivang** [comment]
yeah, I discovered that and it works, when I researched I found a bug report by you that you suggested revision in ckan-canada to use the HTML5 standard validation scheme; -- I tested and the validator does allow dots in the beginning, and also repeated dots, so I guess it's not fully validating but this is a good start.

> `email_validator` can be added to any schemas on any new or existing field. If you're using scheming just add it to the "validators" , e.g. `"validators": "scheming_required email_validator"`

**Comment by sivang** [comment]
Next steps:
* Fix the regexp to exclude malformed email address with dots as per RFC, as does Google in its verification of email addresses.

**Comment by sivang** [comment]
` \A[\w!#$%&'*+/=?`{|}~^-]+(?:\.[\w!#$%&'*+/=?`{|}~^-]+)*@↵
(?:[A-Z0-9-]+\.)+[A-Z]{2,6}\Z `
