### ISSUE TITLE
Bug Have a full list of orgs

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#65]
Jira:
* https://open-data-ed.atlassian.net/browse/OD-112

Users click on list and can't find their specific office. Need to build out the office list.

As a sysadmin I want to have a full list of organization that might exist on portal, so that I can create them and start allocating users there

Checklist

Get the list

Create the orgs

**Comment by zelima** [comment]
FIXED. https://us-ed.l3.ckan.io/organization

TODO: remove test org(s)
