### ISSUE TITLE
existing email validation in ckan is not complete

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#69]
CKAN existing email validation seems to not be complete, and needs fixing of the regexp used.

**Comment by sivang** [comment]
* https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s01.html
*

**Comment by zelima** [comment]
Think this issue does not belong here, but wherever `email_validation` validator is coming  from

**Comment by sivang** [comment]
I'm about to move it to ckan upstream and link that issue most probably.

**Comment by sivang** [comment]
reported upstream:
* https://github.com/ckan/ckan/issues/4719
