### ISSUE TITLE
Quality mark for data profiles

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#83]
Jira:
* https://open-data-ed.atlassian.net/browse/OD-116

Description:
---------------
Establish a visual mark to signify datasets of quality, where quality is defined as having datum(s) that are machine readable and include a full suite of docs.

User story:
-------------- 
As a data steward and a data consumer I wish to easily know which datasets measures up to a standard, namely being machine readable and providing a full suite of docs I wish to be able to easily spot them and possibly search for them.

Checklist:
------------
- [ ] Devise the quality mark icon, position and style within the UX.

- [x] Add required backend logic to "compute" mark/no mark based on said criteria.

- [x] Test

**Comment by sivang** [comment]
Analysis:
- [ ]  Firstly, create a helper function or a toolkit or somesuch, to get a package identifier and return true/false for quality mark as per aforementioned criteria.
- [ ] Figure if this can be an attribute of the dataset (package) object.
- [ ] Integrate this function in all templates like search result and dataset home.

**Comment by sivang** [comment]
Managed to get testing in place, but getting some SQL issues prolly due to DB / Model types / fixtures. @JGulic would love your help

**Comment by zelima** [comment]
@sivang is there anything missing here?

**Comment by sivang** [comment]
Irakli demonstrated today:
- But usdwsd2.0 branch is not merged, so quality mark changes are not evident.
