### ISSUE TITLE
docs resource duplicated in docs/ resource list under uncertain conditions

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#88]
So under certain conditions (which I still need to iron out) the an edited doc resource will get its name duplicated in the list of doc resource.

This is possibly due to failed edits on the resource page, when missing name, or when receiving Internal Server Error again, in an inordinate circumstances.

![image](https://user-images.githubusercontent.com/310789/56911443-93095d00-6ab5-11e9-9646-557f0f5eaac2.png)

Need to reproduce on staging instance.

**Comment by zelima** [comment]
Closing as FIXED for now. Please reopen in case it repeats with steps how to reproduce.
