### ISSUE TITLE
Style tags section by USWDS2.0 (leave the list of Offices in the sidebar)

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#96]
![image](https://user-images.githubusercontent.com/310789/57133929-1627fd00-6dad-11e9-909d-c506c5d46dcd.png)

to

![image](https://user-images.githubusercontent.com/310789/57133959-2809a000-6dad-11e9-908b-3c270703e8bb.png)

**Comment by tanvirchahal** [comment]
@sivang I need to logic behind, to change the generated HTML code to something like  "<div class='tags'"> when it is looping through tags. 

Then I can move forward with styling the tags. 

Currently, every element gets rendered as a checkbox

**Comment by zelima** [comment]
FIXED
