### ISSUE TITLE
Style CKAN Menu by USWDS2.0

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#97]
Enable the USWDS styling onto the Menu.

Jira:
* https://open-data-ed.atlassian.net/browse/OD-149

![image](https://user-images.githubusercontent.com/310789/57134428-d6621500-6dae-11e9-90f2-8eaa7b217a6e.png)

To:

![image](https://user-images.githubusercontent.com/310789/57134449-e974e500-6dae-11e9-96b4-2addb3e55ea6.png)

**Comment by sivang** [comment]
If doing sticky navigation, @jmheaster provided this for 508 compliance:
```"If they are a properly used <navigation> tag and they have an anchor to jump to via the keyboard they should have no 508 issues. Also needs an aria role of "menubar" "```

**Comment by zelima** [comment]
FIXED
