### ISSUE TITLE
Make sure add_dataset style is right (already blue) USWDS2.0 + design

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#98]
![image](https://user-images.githubusercontent.com/310789/57135017-aca9ed80-6db0-11e9-86e3-2620289320be.png)

To:

![image](https://user-images.githubusercontent.com/310789/57135182-2fcb4380-6db1-11e9-94d5-b67d964f29f5.png)

**Comment by zelima** [comment]
FIXED
